import Head from 'next/head'
import VggRunner from '../../dist'


export default function Home() {
  return (
    <>
      <Head>
        <title>VggRunner Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div >
        <VggRunner
          token={'clednbqwy001njxt5owbled9c'}
          width={800}
          height={600}
        />
      </div>

      <div >
        <VggRunner
          token={'clednbqwy001njxt5owbled9c'}
          width={800}
          height={600}
          canvasStyle={{ width: '400px', height: '300px' }}
        />
      </div>

      <div >
        <VggRunner
          token={'clednbqwy001njxt5owbled9c'}
          width={800}
          height={600}
          canvasStyle={{ width: '100vw', height: '100vh' }}
        />
      </div>
    </>
  )
}
