import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import VggRunner from '../../dist'


export default function Home() {
  return (
    <>
      <Head>
        <title>VggRunner Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div style={{ width: '100vw' }}>
          <VggRunner
            token={'clednbqwy001njxt5owbled9c'}
            width={800}
            height={600}
          />
        </div>
      </main>
    </>
  )
}
